{-# OPTIONS --cubical --type-in-type #-}

open import Cubical.Foundations.Everything renaming (Iso to _≅_ ; funExt⁻ to _≡$_)
open import Cubical.Data.List hiding ([_])
open import Cubical.Data.List.Properties
open import Cubical.Data.List.FinData renaming (lookup to _!_)
open import Cubical.Data.Prod
open import Cubical.Data.W.Indexed
open import Cubical.Data.FinData
open import Cubical.Data.Sum
open import Cubical.Data.Sum as ⊎
open import Cubical.Data.Empty
open import Cubical.Data.Nat
open import Cubical.Data.Sigma.Properties
open import Cubical.Foundations.Structure
open import Cubical.Categories.Category
open import Cubical.Categories.Category.Precategory hiding (_[_,_] ; seq')
open import Cubical.Categories.Functor renaming (𝟙⟨_⟩ to ftrId)
open import Cubical.Categories.Instances.Sets
open import Cubical.Categories.Instances.Categories
open import Cubical.Categories.Constructions.Product
open import Cubical.Categories.Monad.Base
open import Cubical.Categories.NaturalTransformation.Base
open import Cubical.Categories.Instances.FunctorAlgebras
open import Cubical.Categories.Instances.EilenbergMoore
open import Cubical.Categories.Adjoint
open import Cubical.Categories.Limits.Initial

open import Mat.Signature
open import Mat.Free.Presentation
import Mat.Free.Term

-- TermQs of the free MAT generated by a free MAT presentation
module Mat.Free.Model {sign : Signature} (fmat : FreeMat sign) where

open Mat.Free.Term fmat

open _≅_
open Category renaming (_∘_ to _⊚_)
open Functor
open NatTrans
open Signature sign
open FreeMat fmat
open Algebra renaming (str to algStr)
open AlgebraHom
open IsEMAlgebra
open NaturalBijection
open _⊣_

-- ModelQs are Eilenberg-Moore algebras of monadTermF
catModelF : Category ℓ-zero ℓ-zero
catModelF = EMCategory monadTermF

ModelF : Type ℓ-zero
ModelF = ob catModelF

ModelFHom : (mFA mFB : ModelF) → Type ℓ-zero
ModelFHom = Hom[_,_] catModelF

-- Forgetful functor sending models to their carrier
ftrForgetModelF : Functor catModelF catMSet
ftrForgetModelF = ForgetEMAlgebra monadTermF

-- Free model functor
ftrFreeModelF : Functor catMSet catModelF
ftrFreeModelF = FreeEMAlgebra monadTermF

adjModelF : ftrFreeModelF ⊣ ftrForgetModelF
adjModelF = emAdjunction monadTermF

-- Recursion/folding (with metavariables) and properties

mFFoldModelF : (msetX : MSet) → (mFA : ModelF)
  → catMSet [ msetX , F-ob ftrForgetModelF mFA ]
  → catModelF [ F-ob ftrFreeModelF msetX , mFA ]
mFFoldModelF msetX mFA = _♯ adjModelF {c = msetX} {d = mFA}

foldModelF : (msetX : MSet) → (mFA : ModelF)
  → catMSet [ msetX , F-ob ftrForgetModelF mFA ]
  → ∀ sort → TermF (mtyp msetX) sort → typ (carrier (fst mFA) sort)
foldModelF msetX mFA f = mFFoldModelF msetX mFA f .carrierHom

mFFoldModelF-nat :  (msetX : MSet) → (mFA mFB : ModelF)
  → (mFG : catModelF [ mFA , mFB ])
  → (f : catMSet [ msetX , F-ob ftrForgetModelF mFA ])
  → mFFoldModelF msetX mFB (_⋆_
      catMSet
      {x = msetX}
      {y = F-ob ftrForgetModelF mFA}
      {z = F-ob ftrForgetModelF mFB}
      f
      (F-hom ftrForgetModelF {x = mFA} {y = mFB} mFG)
    )
  ≡ _⋆_ catModelF {x = F-ob ftrFreeModelF msetX} {mFA} {mFB} (mFFoldModelF msetX mFA f) mFG
mFFoldModelF-nat msetX mFA mFB mFG f =
  sym (adjNatInD' adjModelF {c = msetX} {d = mFA} {d' = mFB} f mFG)

foldModelF-nat : (msetX : MSet) → (mFA mFB : ModelF)
  → (mFG : catModelF [ mFA , mFB ])
  → (f : catMSet [ msetX , F-ob ftrForgetModelF mFA ])
  → foldModelF msetX mFB (λ sort → F-hom ftrForgetModelF {x = mFA} {y = mFB} mFG sort ∘ f sort)
   ≡ (λ sort → F-hom ftrForgetModelF {x = mFA} {y = mFB} mFG sort ∘ foldModelF msetX mFA f sort)
foldModelF-nat msetX mFA mFB mFG f i = mFFoldModelF-nat msetX mFA mFB mFG f i .carrierHom

mFFoldModelF-uniq : (msetX : MSet) → (mFA : ModelF)
  → (f : catMSet [ msetX , F-ob ftrForgetModelF mFA ])
  → (mFG : catModelF [ F-ob ftrFreeModelF msetX , mFA ])
  → (λ sort → mFG .carrierHom sort ∘ pureTermF sort) ≡ f
  → mFFoldModelF msetX mFA f ≡ mFG
mFFoldModelF-uniq msetX mFA f mFG ef =
  mFFoldModelF msetX mFA f
    ≡⟨⟩
  _♯ adjModelF {c = msetX} {d = mFA} f
    ≡⟨ cong (_♯ adjModelF {c = msetX} {d = mFA}) (sym ef) ⟩
  _♯ adjModelF {c = msetX} {d = mFA} (λ sort → mFG .carrierHom sort ∘ pureTermF sort)
    ≡⟨⟩
  _♯ adjModelF {c = msetX} {d = mFA} (_♭ adjModelF {c = msetX} {d = mFA} mFG)
    ≡⟨ adjModelF .adjIso {c = msetX} {d = mFA} .leftInv mFG ⟩
  mFG ∎

foldModelF-uniq : (msetX : MSet) → (mFA : ModelF)
  → (f : catMSet [ msetX , F-ob ftrForgetModelF mFA ])
  → (mFG : catModelF [ F-ob ftrFreeModelF msetX , mFA ])
  → (λ sort → mFG .carrierHom sort ∘ pureTermF sort) ≡ f
  → foldModelF msetX mFA f ≡ mFG .carrierHom
foldModelF-uniq msetX mFA f mFG ef i = mFFoldModelF-uniq msetX mFA f mFG ef i .carrierHom

foldModelF-uniq2 : (msetX : MSet) → (mFA : ModelF)
  → (mFG mFH : catModelF [ F-ob ftrFreeModelF msetX , mFA ])
  → (λ (sort : Sort) → mFG .carrierHom sort ∘ pureTermF sort)
   ≡ (λ (sort : Sort) → mFH .carrierHom sort ∘ pureTermF sort)
  → mFG .carrierHom ≡ mFH .carrierHom
foldModelF-uniq2 msetX mFA mFG mFH e =
  mFG .carrierHom
    ≡⟨ sym (foldModelF-uniq msetX mFA (λ sort → mFG .carrierHom sort ∘ pureTermF sort) mFG refl) ⟩
  foldModelF msetX mFA (λ sort → mFG .carrierHom sort ∘ pureTermF sort)
    ≡⟨ foldModelF-uniq msetX mFA (λ sort → mFG .carrierHom sort ∘ pureTermF sort) mFH (sym e) ⟩
  mFH .carrierHom ∎

-- Sending models of Term1 to models of TermF
module _ where
  model1→F-algStr : ((algebra msetA α) : Model1) → IsAlgebra ftrTermF msetA
  model1→F-algStr (algebra msetA α) sort (varF a) = a
  model1→F-algStr (algebra msetA α) sort (astF (term1 o args)) =
    α sort (term1 o λ p → model1→F-algStr (algebra msetA α) (arity o ! p) (args p))

  model1→F-algStr-joinTermF :
    ((algebra msetA α) : Model1) →
    ∀ sort →
    (tta : TermF (λ sort₁ → TermF (λ sort₂ → fst (msetA sort₂)) sort₁) sort) →
    model1→F-algStr (algebra msetA α) sort (joinTermF sort tta) ≡
    model1→F-algStr (algebra msetA α) sort (mapTermF (model1→F-algStr (algebra msetA α)) sort tta)
  model1→F-algStr-joinTermF (algebra msetA α) sort (varF ta) = refl
  model1→F-algStr-joinTermF (algebra msetA α) sort (astF (term1 o args)) =
    cong (α sort) (cong (term1 o) (funExt λ p → model1→F-algStr-joinTermF (algebra msetA α) (arity o ! p) (args p)))

  model1→F : Model1 → ModelF
  carrier (fst (model1→F (algebra msetA α))) = msetA
  algStr (fst (model1→F (algebra msetA α))) = model1→F-algStr (algebra msetA α)
  str-η (snd (model1→F (algebra msetA α))) = refl
  str-μ (snd (model1→F (algebra msetA α))) = funExt λ sort → funExt λ tta → model1→F-algStr-joinTermF (algebra msetA α) sort tta

  model1→F-ishom : ∀ {(algebra msetA α) (algebra msetB β) : Algebra ftrTerm1} → ((algebraHom f isalgF)
    : Model1Hom (algebra msetA α) (algebra msetB β)) → ∀ sort ta
    → f sort (model1→F-algStr (algebra msetA α) sort ta) ≡ model1→F-algStr (algebra msetB β) sort (mapTermF f sort ta)
  model1→F-ishom {algebra msetA α} {algebra msetB β} (algebraHom f commut) sort (varF a) = refl
  model1→F-ishom {algebra msetA α} {algebra msetB β} (algebraHom f commut) sort (astF (term1 o args)) =
    f sort (α sort (term1 o (λ p → model1→F-algStr (algebra msetA α) (arity o ! p) (args p))))
      ≡⟨ commut' sort (term1 o λ p → model1→F-algStr (algebra msetA α) (arity o ! p) (args p)) ⟩
    β sort (term1 o (λ p → f (arity o ! p) (model1→F-algStr (algebra msetA α) (arity o ! p) (args p))))
      ≡⟨ cong (β sort) (cong (term1 o) (funExt λ p → model1→F-ishom (algebraHom f commut) (arity o ! p) (args p))) ⟩
    β sort (term1 o (λ p → model1→F-algStr (algebra msetB β) (arity o ! p) (mapTermF f (arity o ! p) (args p)))) ∎
    where commut' : ∀ sort ((term1 o' args') : Term1 (mtyp msetA) sort)
                  → f sort (α sort (term1 o' args')) ≡ β sort (term1 o' λ p → f (arity o' ! p) (args' p))
          commut' sort ta i = commut i sort ta

  model1→F-hom : ∀ {m1A m1B} → (m1F : Model1Hom m1A m1B) → ModelFHom (model1→F m1A) (model1→F m1B)
  carrierHom (model1→F-hom {algebra msetA α} {algebra msetB β} (algebraHom f commut)) = f
  strHom (model1→F-hom {algebra msetA α} {algebra msetB β} (algebraHom f commut)) =
    funExt λ sort → funExt λ ta → model1→F-ishom (algebraHom f commut) sort ta

  ftrModel1→F : Functor catModel1 catModelF
  F-ob ftrModel1→F = model1→F
  F-hom ftrModel1→F = model1→F-hom
  F-id ftrModel1→F = AlgebraHom≡ ftrTermF refl
  F-seq ftrModel1→F algF algG = AlgebraHom≡ ftrTermF refl

-- sending models of TermF to models of Term1
module _ where
  nt1→F : NatTrans ftrTerm1 ftrTermF
  N-ob nt1→F msetA sort (term1 o args) = astF (term1 o λ p → varF (args p))
  N-hom nt1→F f = refl

  ftrModelF→1 : Functor catModelF catModel1
  ftrModelF→1 = funcComp {-{D = AlgebrasCategory ftrTermF}{E = catModel1}{C = catModelF}-}
    (AlgebrasFunctor {F = ftrTerm1} {G = ftrTermF} nt1→F)
    (ForgetEM monadTermF)

  modelF→1 : ModelF → Model1
  modelF→1 = F-ob ftrModelF→1

-- Isomorphism components of Model1 ↔ ModelF
module _ where
  ftrModel1→F→1 : funcComp ftrModelF→1 ftrModel1→F ≡ ftrId catModel1
  ftrModel1→F→1 = Functor≡
    (λ (algebra msetA α) → refl)
    (λ where
      {algebra msetA α} {algebra msetB β} (algebraHom f isalgF) → AlgebraHom≡ ftrTerm1 refl
    )

  ftrModelF→1→F : funcComp ftrModel1→F ftrModelF→1 ≡ ftrId catModelF
  ftrModelF→1→F = Functor≡
    (λ where
      (algebra msetA α , isEMA) → Σ≡Prop
        (λ algA → isPropIsEMAlgebra monadTermF)
        (cong (algebra msetA) (funExt λ sort → funExt λ ta → lemma (algebra msetA α) isEMA sort ta))
    )
    (λ where
      {algebra msetA α , isEMA} {algebra msetB β , isEMB} (algebraHom f isalgF) →
        AlgebraHomPathP ftrTermF refl
    )
    where
      open IsEMAlgebra
      lemma : ∀ ((algebra msetA α) : Algebra ftrTermF) (isEMA : IsEMAlgebra monadTermF (algebra msetA α))
        (sort : Sort) (ta : TermF (λ sort₁ → fst (msetA sort₁)) sort) →
        model1→F-algStr (algebra msetA (λ sort' (term1 o args) → α sort' (astF (term1 o λ p → varF (args p))))) sort ta
        ≡ α sort ta
      lemma (algebra msetA α) isEMA sort (varF a) = sym ((str-η isEMA ≡$ sort) ≡$ a)
      lemma (algebra msetA α) isEMA sort (astF (term1 o args)) =
        α sort (astF (term1 o λ p → varF (model1→F-algStr (algebra msetA (λ sort' (term1 o' args') →
                    α sort' (astF (term1 o' λ p₁ → varF (args' p₁))))) (arity o ! p) (args p))))
          ≡⟨ cong (α sort) (cong astF (cong (term1 o) (funExt λ p
              → cong varF (lemma (algebra msetA α) isEMA (arity o ! p) (args p))))) ⟩
        -- (α ∘ Σ var ∘ Σ α) (astF (term1 o args))
        α sort (astF (term1 o λ p → varF (α (arity o ! p) (args p))))
          ≡⟨⟩
        -- (α ∘ Σ Σ* α ∘ Σ var) (astF (term1 o args))
        α sort (astF (term1 o λ p → mapTermF α (arity o ! p) (varF (args p))))
          ≡⟨ sym ((str-μ isEMA ≡$ sort) ≡$ astF (term1 o λ p → varF (args p))) ⟩
        -- (α ∘ Σ µ ∘ Σ var) (astF (term1 o args))
        α sort (joinTermF sort (astF (term1 o λ p → varF (args p))))
          ≡⟨⟩
        α sort (astF (term1 o args)) ∎

-- Model1 ≅ ModelF
open PrecatIso
isoftrModel1≅F : PrecatIso (CatPrecategory ℓ-zero ℓ-zero) catModel1 catModelF
mor isoftrModel1≅F = ftrModel1→F
inv isoftrModel1≅F = ftrModelF→1
sec isoftrModel1≅F = ftrModelF→1→F
ret isoftrModel1≅F = ftrModel1→F→1

-- SyntaxQ object
module _ where

  mFSyntaxF : ModelF
  mFSyntaxF = F-ob ftrFreeModelF msetEmpty

  open NaturalBijection

  isInitial-mFSyntaxF : isInitial catModelF mFSyntaxF
  isInitial-mFSyntaxF = isLeftAdjoint→preservesInitial
    {C = catMSet}
    {D = catModelF}
    ftrFreeModelF
    (ftrForgetModelF , emAdjunction monadTermF)
    msetEmpty
    isInitial-msetEmpty

  m1SyntaxF : Model1
  m1SyntaxF = F-ob ftrModelF→1 mFSyntaxF

  {- Ways to prove initiality of m1SyntaxF:
     - directly (seems stupid)
     - prove that isomorphic precategories are equal
     - prove that mutually inverse functors are adjoint
  -}

